### ISSUE TITLE
有没有调用说明呢？

### ISSUE THREAD

**Issue by danielmlc** [parkingwang/vehicle-keyboard-js#1]
有没有调用说明呢？

**Comment by msdx** [comment]
你想要的是这个[键盘逻辑引擎使用说明](https://github.com/parkingwang/vehicle-keyboard-js#%E9%94%AE%E7%9B%98%E9%80%BB%E8%BE%91%E5%BC%95%E6%93%8E%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E)?
